kubernetesClusterDomain: cluster.local

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# It's best to keep these set as such, unless you're willing to change these in several places.
skaha:
  namespace: skaha-system

# @param securityContext - Optional security context for the container.  This is a security feature to restrict system calls.
# securityContext: {}
#
# Example:
# securityContext:
#   seccompProfile:
#     type: RuntimeDefault

# @param applicationName - The name of the application.  This will rename the underlying WAR file, thus changing the endpoint.  Defaults to storage.
# applicationName: storage

# POSIX Mapper web service deployment
deployment:
  hostname: example.host.com    # Change this!
  storageUI:
    image: images.opencadc.org/client/storage-ui:1.4.1
    imagePullPolicy: IfNotPresent

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # Resources provided to the Storage UI service.
    resources:
      requests:
        memory: "500Mi"
        cpu: "500m"
      limits:
        memory: "850Mi"
        cpu: "500m"

    # Groups that can alter logging.  Empty array means nobody can alter it.
    # loggingGroups: []

    # Dictionary of all VOSpace APIs (Services) available that will be visible on the UI.
    # Format is:
    # backend:
    #   defaultService: cavern
    #   services:
    #     cavern:
    #       resourceID: "ivo://cadc.nrc.ca/arc"
    #       nodeURIPrefix: "vos://cadc.nrc.ca~arc"
    #       userHomeDir: "/home"
    #
    #       # URL to a UI to manage groups.  Used to display in the "Manage Groups" link in the UI.
    #       groupManagementURI: "https://ska-aim.stfc.ac.uk/"
    #
    #       features:
    #         batchDownload: false
    #         batchUpload: false
    #         externalLinks: false
    #         paging: false
    #         directDownload: false

    # ID (URI) of the GMS Service.
    # Example:
    # gmsID: ivo://example.org/gms
    gmsID:

    # OIDC (IAM) server configuration.  These are required
    # oidc:
      # Location of the OpenID Provider (OIdP)
      # uri: https://ska-iam.stfc.ac.uk/
      # The Client ID as listed on the OIdP.
      # clientID: 
      # The Client Secret, which should be generated by the OIdP.
      # clientSecret: 
      # Name of existing secret containing 'clientSecret' key with value of Client Secret, which should be generated by the OIdP.
      # This is an alternative to providing the 'clientSecret' in cleartext in the chart.
      # existingSecretName:
      # Where the OIdP should send the User after successful authentication (redirect_uri)
      # redirectURI:
      # Where to redirect to after the redirectURI callback has completed.  This will usually be the URL to the /storage/list main page.
      # callbackURI: 
      # The standard OpenID scopes for token requests.  This is required.
      # scope: "openid profile offline_access"

    # Set the Registry URL pointing to the desired registry (https:// URL)
    # registryURL: https://example.org/reg

    # This applies to the Storage UID itself.  Meaning, this Pod will be scheduled as described
    # by the nodeAffinity clause.
    # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/
    # nodeAffinity: {}

    # The IdentityManager class handling authentication.  This should generally be left alone
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: storage-ui-cacert-secret

    # Theme to use for presentation layer.
    # Values are:
    # - src   (SRCNet)
    # - canfar  (CANFAR)
    themeName:

# This is a list of tolerations that will be added to the Pod spec of the Storage UI.
# @see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
# 
# Example:
# tolerations:
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
# 
tolerations: []

# secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # storage-ui-cacert-secret:
  #   ca.crt: <base64 encoded ca crt>

# For the token caching
redis:
  image:
    repository: redis
    tag: 8.2.2-bookworm
  architecture: 'standalone'
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
