kubernetesClusterDomain: cluster.local

# Tell Kubernetes to spin up multiple instances.  Defaults to 1.
replicaCount: 1

# @param securityContext - Optional security context for the container.  This is a security feature to restrict system calls.
# See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
#
# Example:
# securityContext:
#   seccompProfile:
#     type: RuntimeDefault
# securityContext: {}

# @param applicationName - The name of the application.  This will rename the underlying WAR file, thus changing the endpoint.  Defaults to posix-mapper.
# applicationName: posix-mapper

# POSIX Mapper web service deployment
deployment:
  hostname: example.org    # Change this!
  posixMapper:
    image: images.opencadc.org/platform/posix-mapper:0.3.2
    imagePullPolicy: Always
    resourceID: ivo://opencadc.org/posix-mapper

    # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
    # oidcURI: https://iam.example.org
    oidcURI:

    # ID (URI) of the GMS Service.
    # gmsID: ivo://example.org/gms
    gmsID:

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # Resources provided to the Skaha service.
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1500Mi"
        cpu: "750m"

    minUID: 10000
    minGID: 900000

    # The IVOA Registry location.
    # registryURL: https://spsrc27.iaa.csic.es/reg
    registryURL:

    # This applies to the POSIX Mapper itself.  Meaning, this Pod will be scheduled as described
    # by the nodeAffinity clause.
    # See https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/
    # nodeAffinity: {}

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: posix-manager-cacert-secret

# This is a list of tolerations that will be added to the Pod spec of the POSIX Mapper API.
# @see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
#
# Example:
# tolerations:
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
#
tolerations: []

  # Specify extra hostnames that will be added to the Pod's /etc/hosts file.  Note that this is in the
  # deployment object, not the posixMapper one.
  #
  # These entries get added as hostAliases entries to the Deployment.
  #
  # Example:
  # extraHosts:
  #   - ip: 127.3.34.5
  #     hostname: myhost.example.org
  #
  # extraHosts: []
secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # posix-manager-cacert-secret:
  #   ca.crt: <base64 encoded ca crt>

# Required.  Database connection information to contain the UID/GID mappings.
# @param postgresql.maxActive - Maximum number of active connections.  Defaults to 8.
# @param postgresql.url - JDBC URL of the PostgreSQL database.  Required.
# @param postgresql.schema - Database schema to use. Required.
# @param postgresql.auth.username - Database username.  Required.
# @param postgresql.auth.password - Database password.  Required.
#
# Example:
# postgresql:
#   maxActive: 8
#   url: jdbc:postgresql://psql.example.org:5432/mapping
#   schema: mapping
#   auth:
#     username: posixmapperuser
#     password: posixmapperpwd
postgresql: {}
