apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: science-portal-tomcat
  name: science-portal-tomcat
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      run: science-portal-tomcat
  template:
    metadata:
      labels:
        run: science-portal-tomcat
    spec:
      {{- with .Values.deployment.sciencePortal.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: regcred
      containers:
      - image: {{ .Values.deployment.sciencePortal.image }}
        imagePullPolicy: {{ .Values.deployment.sciencePortal.imagePullPolicy }}
        name: science-portal-tomcat
        resources:
          requests:
            memory: {{ .Values.deployment.sciencePortal.resources.requests.memory }}
            cpu: {{ .Values.deployment.sciencePortal.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.sciencePortal.resources.limits.memory }}
            cpu: {{ .Values.deployment.sciencePortal.resources.limits.cpu }}
        ports:
        - containerPort: 8080
          protocol: TCP
        {{- with .Values.deployment.sciencePortal.extraPorts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: "/config"
          name: config-volume
        {{- with .Values.deployment.sciencePortal.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podSecurityContext }}
        securityContext:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.sciencePortal.extraEnv }}
        env:
        {{- with .Values.deployment.sciencePortal.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
    {{- range $extraHost := .Values.deployment.extraHosts }}
      hostAliases:
        - ip: {{ $extraHost.ip }}
          hostnames:
            - {{ $extraHost.hostname }}
    {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: science-portal-config
      {{- with .Values.deployment.sciencePortal.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
