apiVersion: config.kueue.x-k8s.io/v1beta1
kind: Configuration

health:
  healthProbeBindAddress: :8081

metrics:
  # Bind to for serving prometheus metrics, set to 0 to disable
  # Maps to metricsService.ClusterIP
  bindAddress: :8080
  # Report the cluster queue resource usage and quotas metrics
  enableClusterQueueResources: true

webhook:
  port: 9443

leaderElection:
  leaderElect: true
  resourceName: c1f6bfd2.kueue.x-k8s.io

controller:
  # Number of concurrent reconciliation allowed for a controller.
  groupKindConcurrency:
    Job.batch: 256
    Pod: 4
    Workload.kueue.x-k8s.io: 256
    LocalQueue.kueue.x-k8s.io: 256
    ClusterQueue.kueue.x-k8s.io: 256
    ResourceFlavor.kueue.x-k8s.io: 4

# Client connection details for the k8s_apiserver
clientConnection:
  # queries/second allowed for k8s_apiserver
  qps: 64
  # extra queries to accumulate when a client is exceeding its rate.
  burst: 128


# pprof is a tool for visualization and analysis of profiling data enabled by setting the bind address.
#pprofBindAddress: :8083

# Wait for admitted workload to reach PodsReady=true. When enabled,
# if  pods exceeds the timeout, it will be evicted and requeued in the same
# cluster queue for backoffLimitCount times
waitForPodsReady:
  enable: false
  timeout: 5m
  blockAdmission: false
  requeuingStrategy:
    timestamp: Eviction
    backoffLimitCount: null # null indicates infinite requeuing
    backoffBaseSeconds: 60
    backoffMaxSeconds: 3600


# Controls whether or not Kueue reconciles jobs that don't set the annotation kueue.x-k8s.io/queue-name.
# If set to true, then those jobs will be suspended and never started unless they are assigned a queue
# and eventually admitted. This also applies to jobs created before starting the kueue controller.
# Defaults to false; therefore, those jobs are not managed and if they are created unsuspended,
# they will start immediately.
manageJobsWithoutQueueName: false

#! TODO: Setyp proper internal cert management with RCS
# https://kueue.sigs.k8s.io/docs/reference/kueue-config.v1beta1/#InternalCertManagement
# internalCertManagement:
#   enable: false
#   webhookServiceName: ""
#   webhookSecretName: ""

integrations:
  # List of framewor to be integrated with Kueue.
  frameworks:
  - "batch/job"
  # - "kubeflow.org/mpijob"
  # - "ray.io/rayjob"
  # - "ray.io/raycluster"
  # - "jobset.x-k8s.io/jobset"
  # - "kubeflow.org/mxjob"
  # - "kubeflow.org/paddlejob"
  # - "kubeflow.org/pytorchjob"
  # - "kubeflow.org/tfjob"
  # - "kubeflow.org/xgboostjob"
  # - "pod"
  # - "deployment"
  # externalFrameworks:
  # - "Foo.v1.example.com"

  # kueue controller behaviour for pod objects
  podOptions:
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: [ skaha-workload, canfar-b-workload ]

# FairSharing enables fair sharing for all cohorts.
# See https://kueue.sigs.k8s.io/docs/reference/kueue-config.v1beta1/#FairSharing
#fairSharing:
#  enable: true
#  preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]

# Additional configuration options for handling the resources.
#resources:
#  excludeResourcePrefixes: []
# transformations:
# - input: nvidia.com/mig-4g.5gb
#   strategy: Replace | Retain
#   outputs:
#     example.com/accelerator-memory: 5Gi
#     example.com/accelerator-gpc: 4
