apiVersion: v1
kind: Service
metadata:
  name: storage-ui-tomcat-svc
  namespace: {{ .Release.Namespace }}
  labels:
    run: storage-ui-tomcat-svc
spec:
  ports:
  - port: 8080
    name: http-connection
    protocol: TCP
  {{ with .Values.service }}
    {{ with .extraPorts }}
  {{- toYaml . | nindent 2 }}
    {{- end }}
  {{- end }}
  selector:
    run: storage-ui-tomcat
