apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-skaha-ingress
  namespace: {{ .Values.skaha.namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - host: {{ .Values.deployment.hostname }}
    http:
      paths:
      - path: /skaha
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-skaha-tomcat-svc
            port:
              number: 8080
