{{ $currContext := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-skaha-config
  namespace: {{ .Values.skaha.namespace }}
data:
{{ tpl ($.Files.Glob "config/*").AsConfig . | indent 2 }}

# Treat IngressRoute configuration as a Helm Template.
# This is allowed to be able to specify TLS specification in the IngressRoute.
# jenkinsd 2025.07.15
#
{{ tpl ($.Files.Glob "skaha-config/ingress*.yaml").AsConfig . | indent 2 }}

{{ range $path, $_ :=  $.Files.Glob "skaha-config/launch*.yaml" }}
  {{ base $path }}: |
  {{- tpl ($.Files.Get $path) $currContext | nindent 4 }}
{{ end }}
{{ range $path, $_ :=  $.Files.Glob "skaha-config/service*.yaml" }}
  {{ base $path }}: |
  {{- tpl ($.Files.Get $path) $currContext | nindent 4 }}
{{ end }}
{{ ($.Files.Glob "skaha-config/*.json").AsConfig | indent 2 }}
{{- include "utils.extraConfig" (dict "extraConfigData" .Values.deployment.skaha.extraConfigData) -}}
{{- (.Files.Glob "image-cache/*").AsConfig | nindent 2 }}
