{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-skaha-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - host: {{ .Values.deployment.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path | default "/skaha"}}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-skaha-tomcat-svc
            port:
              number: {{ .Values.service.port | default "8080" }}
{{- end }}
