{{- with required "PostgreSQL Database configuration is required." .Values.postgresql }}
{{- if .install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posix-mapper-postgres
  namespace: {{ $.Values.skaha.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posix-mapper-postgres
  template:
    metadata:
      labels:
        app: posix-mapper-postgres
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: {{ .image | default "postgres:13.20" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: posix-mapper-postgres-config
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresinit
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          securityContext:
            allowPrivilegeEscalation: false
      # Maintain the same tolerations as the "parent" POSIX Mapper API.
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: postgresdb
          {{- toYaml .storage.spec | nindent 10 }}
        - name: postgresinit
          configMap:
            name: posix-mapper-postgres-init
{{- end }}
{{- end }}