name: Renovate

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for Manual Renovate Run'
        required: true
        type: string
  repository_dispatch:
    types: [renovate]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovation Dispatch Event
        id: renovate-dispatch-event
        run: |
          echo "=== Renovation Dispatch Event ==="
          echo "Event: ${{ github.event_name }}"
          echo "Payload: ${{ toJson(github.event) }}"
          echo "=== End Payload ==="

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@aec779d4f7845f8431ddf403cf9659d4702ddde0 # v43.0.18
        with:
          configurationFile: .github/renovate-config.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          token: ${{ secrets.RENOVATE_TOKEN }}
