name: Renovate

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual renovate run'
        required: true
        type: string

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Cache Renovate Docker Image
        uses: docker/build-push-action@v6.18.0
        with:
          pull: true
          tags: ghcr.io/renovatebot/renovate:41
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@aec779d4f7845f8431ddf403cf9659d4702ddde0 # v43.0.18
        with:
          configurationFile: .github/renovate-config.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          renovate-image: ghcr.io/renovatebot/renovate:41
          token: ${{ secrets.RENOVATE_TOKEN }}
